# PyTorch

In [ ]:
# PyTorch Version 확인
import torch

print(torch.__version__)

### PyTorch Tensor Data Types (dtype)

| <div align="center">Data type</div> | <div align="center">dtype</div> | <div align="center">CPU tensor</div> | <div align="center">GPU tensor</div> |
|-------------------------------------|-----------------------------------------------------------------|-------------------------|---------------------------|
|8-bit Integer (정수형)                 |`torch.int8`                                                     |`torch.CharTensor`       |`torch.cuda.CharTensor`    |
|8-bit Integer (정수형) (unsigned)      |`torch.uint8`                                                    |`torch.ByteTensor`       |`torch.cuda.ByteTensor`    |
|16-bit Integer (정수형)                |`torch.int16` or `torch.short`                                   |`torch.ShortTensor`      |`torch.cuda.ShortTensor`   |
|32-bit Integer (정수형)                |`torch.int32` or `torch.int`                                     |`torch.IntTensor`        |`torch.cuda.IntTensor`     |
|64-bit Integer (정수형)                |***Default(Integer)***, `torch.int64` or `torch.long`            |`torch.LongTensor`       |`torch.cuda.LongTensor`    |
|16-bit Floating Points (부동 소수점형)   |`torch.float16` or `torch.half`                                  |`torch.HalfTensor`       |`torch.cuda.HalfTensor`    |
|32-bit Floating Points (부동 소수점형)   |***Default(Floating Points)***, `torch.float32` or `torch.float` |`torch.FloatTensor`      |`torch.cuda.FloatTensor`   |
|64-bit Floating Points (부동 소수점형)   |`torch.float64` or `torch.double`                                |`torch.DoubleTensor`     |`torch.cuda.DoubleTensor`  |

In [ ]:
# 초기화 되지 않은 Tensor
x = torch.empty(4, 2)
print('torch.empty(4, 2)')
print(x, end='\n\n')

# 무작위로 초기화된 Tensor
x = torch.rand(4, 2)
print('torch.rand(4, 2)')
print(x, end='\n\n')

# Data type이 long이고, 0으로 채워진 Tensor
x = torch.zeros(4, 2, dtype=torch.long)
print('torch.zeros(4, 2, dtype=torch.long)')
print(x, end='\n\n')

# 2x4 크기, double type, 1로 채워진 Tensor
x = torch.ones(2, 4, dtype=torch.double)
print('torch.ones(2, 4, dtype=torch.double)')
print(x, end='\n\n')

# 사용자가 입력한 값으로 Tensor 초기화
my_tensor = torch.tensor([3, 2.3])
print('torch.tensor([3, 2.3]')
print(my_tensor, end='\n\n')

# (new_) 기존 Tensor의 dtype 및 device 속성을 유지한 채 새로운 Tensor를 생성
x = my_tensor.new_zeros(3, 3)
print('my_tensor.new_zeros(3, 3)')
print(x, end='\n\n')

x = my_tensor.new_ones(3, 3)
print('my_tensor.new_ones(3, 3)')
print(x, end='\n\n')

# (_like) 기존 Tensor의 shape은 유지한 채 새로운 Tensor를 생성
x = torch.randn_like(my_tensor, dtype=torch.double)
print('torch.randn_like(my_tensor, dtype=torch.double)')
print(x, end='\n\n')

x = torch.zeros_like(my_tensor, dtype=torch.long)
print('torch.zeros_like(my_tensor, dtype=torch.long)')
print(x, end='\n\n')

# Tensor의 shape 확인
x = torch.rand(5, 2, 3)
print(x.size())
print(list(x.size()))

# Tensor의 dtype 확인
print(x.dtype)

In [59]:
ft = torch.IntTensor([1, 2, 3])
print(ft)
print(ft.dtype)

# Tensor의 Type 변경
print(ft.short())
print(ft.long())
print(ft.half())
print(ft.float())
print(ft.double())

tensor([1, 2, 3], dtype=torch.int32)
torch.int32
tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3])
tensor([1., 2., 3.], dtype=torch.float16)
tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)


### CUDA Tensor