# PyTorch Tensor 객체의 Shape 관련 Function 및 Method 정리

## 1. Shape 변경 (Memory 연속성 여부에 주의)

### 1.1 `view`
- **기능**: 텐서의 shape을 변경합니다.
- **특징**: 데이터 순서는 그대로 유지하며, 연속적인 메모리 구조가 필요합니다. (차원이 재배열 된 경우에 view()를 사용하면 오류 발생)
- **메모리**: 데이터 복사 없이 원본 데이터를 참조합니다.
- **인자**: `*shape`
  - 텐서의 새로운 shape을 정의하는 정수형 크기 값
- **사용 예시**: 텐서를 `(4, 2)` shape으로 변경하기.
  ```python
  tensor = torch.arange(8)  # (8)
  """
  tensor([0, 1, 2, 3, 4, 5, 6, 7])
  """
  
  reshaped_tensor = tensor.view(4, 2)  # (4, 2)
  """
  tensor([[0, 1], 
          [2, 3], 
          [4, 5], 
          [6, 7]])
  """
  ```

### 1.2 `reshape`
- **기능**: `view`와 비슷하게 텐서의 shape을 변경합니다.
- **특징**: 메모리 구조에 덜 의존적이어서 더 유연하게 shape을 변경할 수 있으며, 필요시 데이터 복사가 일어날 수 있습니다.
- **메모리**: 데이터가 연속적이라면 'view'를 반환하여 데이터 복사가 발생하지 않지만, 데이터가 불연속적이라면 데이터 복사 및 메모리 할당이 발생합니다.
- **인자**: `*shape`
  - 텐서의 새로운 shape을 정의하는 정수형 크기 값
- **사용 예시**: 텐서를 `(2, 4)` shape으로 변경하기.
  ```python
  tensor = torch.arange(8)  # (8)
  """
  tensor([0, 1, 2, 3, 4, 5, 6, 7])
  """

  reshaped_tensor = tensor.reshape(2, 4)  # (2, 4)
  """
  tensor([[0, 1, 2, 3], 
          [4, 5, 6, 7]])
  """
  ```

## 2. 기타

### 2.1 `contiguous`
- **기능**: 텐서가 연속된 메모리 위치에 저장되어 있는지 확인하고, 그렇지 않은 경우 새로운 연속적인 메모리를 할당하여 동일한 텐서를 반환합니다.
- **특징**: 일부 텐서 연산 (예: `view`)은 텐서가 연속적 메모리 상에 있어야만 정상적으로 작동합니다. 만약 텐서가 메모리 상에 연속적이지 않다면, `contiguous()`를 사용하여 연속적인 메모리 형태로 변환할 수 있습니다.
- **메모리**: 데이터 복사 및 메모리 할당이 발생합니다.
- **사용 예시**:
  ```python
  tensor = torch.randn(2, 3, 4).permute(1, 0, 2)  # permute() 사용으로 인하여 메모리가 불연속적인 텐서
  print(tensor.is_contiguous())  # False

  contiguous_tensor = tensor.contiguous().view(4, 2, 3)  # 메모리가 연속적인 텐서로 변환 후 view() 사용 가능
  print(contiguous_tensor.is_contiguous())  # True
  ```

### 2.2 `clone`

- **기능**: 텐서의 데이터를 새로운 메모리 공간에 복사하여 원본과 동일한 속성을 갖지만 독립적인 텐서를 생성합니다.
- **특징**: 원본 텐서가 변경되어도 클론된 텐서에는 영향을 주지 않습니다. `clone()`은 데이터만 복사하며, 연산 그래프와 연결 상태는 유지됩니다. 만약 연산 그래프와 분리하려면 `detach()`를 추가로 사용해야 합니다.
- **메모리**: 데이터 복사 및 메모리 할당이 발생합니다.
- **사용 예시**:
  ```python
  tensor = torch.arange(1, 7).view(2, 3)
  """
  tensor([[ 1, 2, 3],
          [ 4, 5, 6]])
  """

  view_tensor = tensor.view(3, 2)  # 메모리 공유
  cloned_tensor = tensor.clone()   # 메모리 독립적

  tensor[0, 0] = 99

  print(tensor)
  """
  tensor([[99,  2,  3],
          [ 4,  5,  6]])
  """
  print(view_tensor)
  """
  tensor([[99,  2],
         [ 3,  4],
         [ 5,  6]])
  """
  print(cloned_tensor)
  """
  tensor([[1, 2, 3],
          [4, 5, 6]])
  """
  ```

## 3. 차원 재배열

### 3.1 `permute`
- **기능**: 텐서의 차원 순서를 변경합니다.
- **특징**: 지정한 순서에 따라 차원을 재배열하며, 데이터는 그대로 유지됩니다.
- **메모리**: 데이터 복사 없이 원본 데이터를 참조합니다.
- **인자**: `*dims`
  - 텐서의 차원을 재배열할 새로운 순서
- **사용 예시**: `(2, 3, 4)` shape의 텐서를 `(2, 4, 3)` shape으로 차원 재배열하기.
  ```python
  tensor = torch.arange(24).view(2, 3, 4)  # (2, 3, 4)
  """
  tensor([[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7],
           [ 8,  9, 10, 11]],

          [[12, 13, 14, 15],
           [16, 17, 18, 19],
           [20, 21, 22, 23]]])
  """

  permuted_tensor = tensor.permute(0, 2, 1)  # (2, 4, 3)
  """
  tensor([[[ 0,  4,  8],
           [ 1,  5,  9],
           [ 2,  6, 10],
           [ 3,  7, 11]],

          [[12, 16, 20],
           [13, 17, 21],
           [14, 18, 22],
           [15, 19, 23]]])
  """
  ```

### 3.2 `transpose`
- **기능**: 두 개의 차원을 교환하여 위치를 바꿉니다.
- **특징**: `permute`와 유사하지만, 두 개의 차원만 바꿀 때 사용하기 간편합니다.
- **메모리**: 데이터 복사 없이 원본 데이터를 참조합니다.
- **인자**: `dim0`, `dim1`
  - 교환하고자 하는 두 차원의 인덱스 값
- **사용 예시**: `(2, 3, 4)` shape의 텐서를 `(2, 4, 3)` shape으로 차원 교환하기.
  ```python
  tensor = torch.arange(24).view(2, 3, 4)  # (2, 3, 4)
  """
  tensor([[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7],
           [ 8,  9, 10, 11]],

          [[12, 13, 14, 15],
           [16, 17, 18, 19],
           [20, 21, 22, 23]]])
  """

  transposed_tensor = tensor.transpose(1, 2)  # (2, 4, 3)
  """
  tensor([[[ 0,  4,  8],
           [ 1,  5,  9],
           [ 2,  6, 10],
           [ 3,  7, 11]],

          [[12, 16, 20],
           [13, 17, 21],
           [14, 18, 22],
           [15, 19, 23]]])
  """
  ```

## 4. 차원 추가 및 제거

### 4.1 `squeeze`와 `unsqueeze`
- **기능**:
  - `squeeze`: 크기가 1인 차원을 제거합니다.
  - `unsqueeze`: 지정한 위치에 크기가 1인 차원을 추가합니다.
- **특징**: 데이터 구조는 그대로 유지하면서, 특정 차원의 크기를 1로 만들거나 제거할 수 있습니다.
- **메모리**: 데이터 복사 없이 원본 데이터를 참조합니다.
- **인자**: `dim`
  - 제거하고자 하는 크기가 1인 차원의 인덱스, 지정하지 않으면 크기가 1인 모든 차원을 제거 (squeeze)
  - 크기가 1인 차원을 추가하고자 하는 위치의 인덱스 (unsqueeze)
- **사용 예시**:
  ```python
  tensor = torch.arange(1, 9).view(1, 2, 4)  # (1, 2, 4)
  """
  tensor([[[1, 2, 3, 4],
           [5, 6, 7, 8]]])
  """

  squeezed_tensor = tensor.squeeze(0)  # (2, 4)
  """
  tensor([[1, 2, 3, 4],
          [5, 6, 7, 8]])
  """
  unsqueezed_tensor = tensor.unsqueeze(2)  # (1, 2, 1, 4)
  """
  tensor([[[[1, 2, 3, 4]],

           [[5, 6, 7, 8]]]])
  """
  ```

## 5. Tensor 결합 및 확장

### 5.1 `cat` (concatenate)
- **기능**: 지정한 차원을 기준으로 여러 텐서를 연결합니다.
- **특징**: 연결하려는 차원의 크기는 일치해야 합니다.
- **메모리**: 데이터 복사 및 메모리 할당이 발생합니다.
- **인자**:
  - `tensors`: 연결하고자 하는 텐서들
  - `dim`: 연결 기준이 되는 차원의 인덱스
- **사용 예시**: `(2, 4)` shape의 텐서 두 개를 `(4, 4)`, `(2, 8)` shape으로 연결하기.
  ```python
  tensor1 = torch.arange(1, 9).view(2, 4)  # (2, 4)
  """
  tensor([[1, 2, 3, 4],
          [5, 6, 7, 8]])
  """
  tensor2 = torch.arange(9, 17).view(2, 4)  # (2, 4)
  """
  tensor([[ 9, 10, 11, 12],
          [13, 14, 15, 16]])
  """

  concatenated_tensor_0 = torch.cat((tensor1, tensor2), 0)  # (4, 4)
  """
  tensor([[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]])
  """
  concatenated_tensor_1 = torch.cat((tensor1, tensor2), 1)  # (2, 8)
  """
  tensor([[ 1,  2,  3,  4,  8,  9, 10, 11],
          [ 5,  6,  7,  8, 12, 13, 14, 15]])
  """
  ```

### 5.2 `stack`
- **기능**: 여러 텐서를 새로운 차원에서 쌓아 결합합니다.
- **특징**: 결합하려는 텐서들의 모든 차원이 동일해야 하며, 지정한 새로운 차원에서 스택을 형성합니다.
- **메모리**: 데이터 복사 및 메모리 할당이 발생합니다.
- **인자**:
  - `tensors`: 결합하고자 하는 텐서들의 리스트
  - `dim`: 새로 추가되는 차원의 인덱스
- **사용 예시**: `(3, 4)` shape의 텐서 두 개를 `(2, 3, 4)` shape으로 결합하기.
  ```python
  tensor1 = torch.arange(1, 13).view(3, 4)  # (3, 4)
  """
  tensor([[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]])
  """
  tensor2 = torch.arange(13, 25).view(3, 4)  # (3, 4)
  """
  tensor([[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]])
  """

  stacked_tensor = torch.stack((tensor1, tensor2), 0)  # (2, 3, 4)
  """
  tensor([[[ 1,  2,  3,  4],
           [ 5,  6,  7,  8],
           [ 9, 10, 11, 12]],

          [[13, 14, 15, 16],
           [17, 18, 19, 20],
           [21, 22, 23, 24]]])
  """
  ```

### 5.3 `repeat`
- **기능**: 텐서를 지정된 횟수만큼 반복하여 크기를 확장합니다.
- **특징**: 데이터의 실제 복사가 일어납니다. 메모리를 추가적으로 사용하여 확장된 형태의 텐서를 생성합니다.
- **메모리**: 데이터 복사가 발생하여 메모리 사용량이 증가합니다.
- **인자**: `*repeats`
  - 각 차원에 대해 반복할 횟수를 정의하는 정수형 크기 값
- **사용 예시**: `(2, 3)` shape의 텐서를 `(6, 15)` shape으로 반복하기.
  ```python
  tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])  # (2, 3)
  """
  tensor([[1, 2, 3],
          [4, 5, 6]])
  """

  repeated_tensor = tensor.repeat(3, 5)  # (6, 15)
  """
  tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
          [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6],
          [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
          [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6],
          [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
          [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])
  """
  ```

### 5.4 `expand`
- **기능**: 텐서의 크기가 1인 차원을 확장합니다.
- **특징**: 데이터 복사 없이 원래 텐서를 참조하는 형태로 확장됩니다. 크기가 1이 아닌 차원은 확장할 수 없습니다.
- **메모리**: 데이터 복사 없이 브로드캐스팅된 방식으로 작동합니다.
- **인자**: `*shape`
  - 확장된 텐서의 최종 shape을 정의하는 정수형 크기 값
- **사용 예시**: `(1, 3)` shape의 텐서를 `(4, 3)` shape으로 확장하기.
  ```python
  tensor = torch.tensor([[1, 2, 3]])  # (1, 3)
  """
  tensor([[1, 2, 3]])
  """
  expanded_tensor = tensor.expand(4, 3)  # (4, 3)
  """
  tensor([[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]])
  """
  ```